.PHONY: all run gdb runvcd clean

CROSS_COMPILE := loongarch32r-linux-gnusf-
ASFLAGS       += -O0
LDFLAGS       += 



all: $(addprefix Makefile., $(ALL))
	@echo "" $(ALL)







clean:
	rm -rf Makefile.* build/
